In [1]:
import json
from pandas import json_normalize
import pandas as pd
from datetime import date

Nous avons plusieurs fichiers dans lesquelles sont listées les offres d'alternances (provenant de l'api la bonne alternance). En effet, nous étions limitées à un rayon kilométrique de 200km. Nous avons donc dû en sortir plusieurs par rapport à différents points de la France pour essayer de couvrir la totalité du territoire.

In [2]:
with open("Data/nord.json", "r", encoding="utf-8") as read_file:
    data_nord = json.load(read_file)
with open("Data/nord_est.json", "r", encoding="utf-8") as read_file:
    data_nord_est = json.load(read_file)
with open("Data/nord-ouest.json", "r", encoding="utf-8") as read_file:
    data_nord_ouest = json.load(read_file)
with open("Data/centre.json", "r", encoding="utf-8") as read_file:
    data_centre = json.load(read_file)
with open("Data/sud_est.json", "r", encoding="utf-8") as read_file:
    data_sud_est = json.load(read_file)
with open("Data/sud_ouest.json", "r", encoding="utf-8") as read_file:
    data_sud_ouest = json.load(read_file)

In [3]:
data_centre.keys()

dict_keys(['peJobs', 'lbaCompanies', 'lbbCompanies'])

peJobs : les offres d'emploir provenant de pôle emploi

lbaCompanies : les offres d'emploi provenant de la bonna alternance

lbbCompanies : les offres d'emploi provenant de la bonne boîte

On utilise ici que les données provenant de peJobs car les autres source ne donne pas la date de création de l'offre, nous ne pourrions donc pas recouper ces données avec les données covid par date.

In [4]:
df_list = []

#On concaténe les différents listes d'offres d'emploi provenant des différents fichiers

df_list.append(json_normalize(data_centre['peJobs']['results']))

df_list.append(json_normalize(data_nord_est['peJobs']['results']))

df_list.append(json_normalize(data_nord_ouest['peJobs']['results']))

df_list.append(json_normalize(data_sud_est['peJobs']['results']))

df_list.append(json_normalize(data_sud_ouest['peJobs']['results']))

df_list.append(json_normalize(data_nord['peJobs']['results']))

jobs_df = pd.concat(df_list, axis=0)

jobs_df

,ideaType,ideaWeight,title,longTitle,id,diplomaLevel,diploma,cfd,rncpCode,rncpLabel,...,job.description,job.contractType,job.contractDescription,job.duration,contact.name,contact.info,contact,contact.email,company.description,company.logo
0,peJob,1000.0,coiffeur/coiffeuse en alternance (CAP) (H/F),None,None,None,None,None,None,None,...,salon FRANCK PROVOSTsitué en plein centre vill...,CDD,Contrat à durée déterminée - 24 Mois,35H Travail le samedi,NaN,NaN,NaN,NaN,NaN,NaN
1,peJob,1000.0,Coiffeur / Coiffeuse,None,None,None,None,None,None,None,...,Apprenti (e) coiffeur (se)\nSuivant modalités ...,CDD,Contrat à durée déterminée - 24 Mois,35H Horaires normaux,Pôle Emploi Arpajon,"2 ROUTE d'Egly\n91290 ARPAJON\nPour postuler, ...",NaN,NaN,NaN,NaN
2,peJob,1000.0,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,None,None,None,None,None,None,None,...,"Dans ce cadre, vous serez amené(e) à :\n\nPart...",CDD,Contrat à durée déterminée - 24 Mois,35H Horaires normaux,NaN,https://sanofi.wd3.myworkdayjobs.com/StudentPr...,NaN,NaN,NaN,NaN
3,peJob,1000.0,Préparateur / Préparatrice de commandes (H/F),None,None,None,None,None,None,None,...,Description du poste :\nSTEF recrute pour sa f...,CDD,Contrat à durée déterminée - 12 Mois,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,peJob,1000.0,Agent / Agente logistique en magasinage (H/F),None,None,None,None,None,None,None,...,Description du poste :\nSTEF recrute pour sa f...,CDD,Contrat à durée déterminée - 12 Mois,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,peJob,444.4,Conseiller / Conseillère en organisation d'évè...,None,None,None,None,None,None,None,...,POSTE : Assistant Événementiel H/F\nPROFIL : E...,CDD,Contrat à durée déterminée - 12 Mois,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,peJob,311.8,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,None,None,None,None,None,None,None,...,"Dans ce cadre, vous serez amené(e) à :\n\nPart...",CDD,Contrat à durée déterminée - 24 Mois,35H Horaires normaux,NaN,https://sanofi.wd3.myworkdayjobs.com/StudentPr...,NaN,NaN,NaN,NaN
97,peJob,100.0,Assistant Social Media Manager H/F,None,None,None,None,None,None,None,...,Le secteur du tourisme vous passionne et vous ...,CDD,Contrat à durée déterminée - 12 Mois,Horaires normaux,NaN,NaN,NaN,NaN,NaN,NaN
98,peJob,100.0,Alternance - Attaché de presse F/H (H/F),None,None,None,None,None,None,None,...,Vous avez envie de contribuer à la promotion d...,CDD,Contrat à durée déterminée - 12 Mois,Horaires normaux,NaN,NaN,NaN,NaN,NaN,NaN
99,peJob,100.0,Alternant chargé de communication F/H (H/F),None,None,None,None,None,None,None,...,Acteur de référence des services immobilier ré...,CDD,Contrat à durée déterminée - 12 Mois,35 H Horaires normaux,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
jobs_df[['job.creationDate','title','place.city','company.name','place.latitude', 'place.longitude' ]]

,job.creationDate,title,place.city,company.name,place.latitude,place.longitude
0,2021-04-06T14:08:56.000Z,coiffeur/coiffeuse en alternance (CAP) (H/F),91 - MONTGERON,FRANCK PROVOST,48.704816,2.455399
1,2021-02-04T17:25:49.000Z,Coiffeur / Coiffeuse,91 - OLLAINVILLE,Salon des terrasses,48.599400,2.227350
2,2021-04-08T15:55:42.000Z,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,69 - NEUVILLE SUR SAONE,SANOFI-AVENTIS GROUPE,45.878996,4.838026
3,2021-03-21T08:59:42.000Z,Préparateur / Préparatrice de commandes (H/F),91 - ATHIS MONS,NaN,48.708960,2.384591
4,2021-03-22T17:45:11.000Z,Agent / Agente logistique en magasinage (H/F),91 - ATHIS MONS,NaN,48.708960,2.384591
...,...,...,...,...,...,...
95,2021-03-24T03:12:02.000Z,Conseiller / Conseillère en organisation d'évè...,44 - ST HERBLAIN,NaN,47.211390,-1.651111
96,2021-04-08T15:55:42.000Z,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,69 - NEUVILLE SUR SAONE,SANOFI-AVENTIS GROUPE,45.878996,4.838026
97,2021-04-08T06:20:42.000Z,Assistant Social Media Manager H/F,75 - PARIS 19,NaN,2.345581,48.859295
98,2021-04-10T10:56:35.000Z,Alternance - Attaché de presse F/H (H/F),75 - PARIS 19,NaN,2.345581,48.859295
99,2021-03-24T07:45:52.000Z,Alternant chargé de communication F/H (H/F),75 - PARIS 08,NaN,2.345581,48.859295

Le fichier covid n'ayant pas la donnée par ville, on va ajouter les départements pour pouvoir faire le lien par département.

In [6]:
def get_department(x):
    return((x[:2]))

jobs_df['place.departement'] = jobs_df['place.zipCode'].apply(str).apply(get_department)

Pour comparer avec le taux d'incidence covid par mois, on ajoute une colonne moi dans le dataframe

In [7]:
def get_month(x):
    return(x[0:7])

jobs_df['month'] = jobs_df['job.creationDate'].apply(get_month)

In [8]:
filtered_jobs_df = jobs_df[['job.creationDate','month','title','place.city','place.zipCode','place.departement','company.name']]

filtered_jobs_df

,job.creationDate,month,title,place.city,place.zipCode,place.departement,company.name
0,2021-04-06T14:08:56.000Z,2021-04,coiffeur/coiffeuse en alternance (CAP) (H/F),91 - MONTGERON,91230,91,FRANCK PROVOST
1,2021-02-04T17:25:49.000Z,2021-02,Coiffeur / Coiffeuse,91 - OLLAINVILLE,91340,91,Salon des terrasses
2,2021-04-08T15:55:42.000Z,2021-04,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,69 - NEUVILLE SUR SAONE,69250,69,SANOFI-AVENTIS GROUPE
3,2021-03-21T08:59:42.000Z,2021-03,Préparateur / Préparatrice de commandes (H/F),91 - ATHIS MONS,91200,91,NaN
4,2021-03-22T17:45:11.000Z,2021-03,Agent / Agente logistique en magasinage (H/F),91 - ATHIS MONS,91200,91,NaN
...,...,...,...,...,...,...,...
95,2021-03-24T03:12:02.000Z,2021-03,Conseiller / Conseillère en organisation d'évè...,44 - ST HERBLAIN,44800,44,NaN
96,2021-04-08T15:55:42.000Z,2021-04,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,69 - NEUVILLE SUR SAONE,69250,69,SANOFI-AVENTIS GROUPE
97,2021-04-08T06:20:42.000Z,2021-04,Assistant Social Media Manager H/F,75 - PARIS 19,75019,75,NaN
98,2021-04-10T10:56:35.000Z,2021-04,Alternance - Attaché de presse F/H (H/F),75 - PARIS 19,75019,75,NaN
99,2021-03-24T07:45:52.000Z,2021-03,Alternant chargé de communication F/H (H/F),75 - PARIS 08,75008,75,NaN

La date de création d'offres d'alternance la plus ancienne étant août 2020, il faut se restreindre dans notre fichier covid à prendre les données qu'à partir de ce mois-ci

In [9]:
data_covid = pd.read_csv('Data/table-indicateurs-open-data-dep-2021-04-09-20h00.csv')

covid_df = pd.DataFrame(data_covid)

C:\Users\phola\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Pour pouvoir lier les deux fichiers entre eux, on ajoute une colonne mois au fichier covid.

In [10]:
covid_df['month'] = covid_df['date'].apply(get_month)

Transformer les dates dans le bon format dans le but de pouvoir appliquer un filtre

In [11]:
covid_df['date'] = pd.to_datetime(covid_df['date'], format='%Y-%m-%d')

In [12]:
covid_df[['dep', 'date', 'month', 'tx_incid']]

       dep       date    month   tx_incid
0       01 2020-03-18  2020-03        NaN
1       01 2020-03-19  2020-03        NaN
2       01 2020-03-20  2020-03        NaN
3       01 2020-03-21  2020-03        NaN
4       01 2020-03-22  2020-03        NaN
...    ...        ...      ...        ...
39183  976 2021-04-05  2021-04  51.168100
39184  976 2021-04-06  2021-04  53.315013
39185  976 2021-04-07  2021-04        NaN
39186  976 2021-04-08  2021-04        NaN
39187  976 2021-04-09  2021-04        NaN

[39188 rows x 4 columns]

Création d'un filtre pour n'obtenir les dates qu'à partir du 01-08-2021

In [13]:
mask = (covid_df['date'] > '2020-08-1') & (covid_df['date'] <= '2021-04-11')
filtered_covid_df = covid_df.loc[mask]
data_covid_def = filtered_covid_df[['dep', 'date', 'month', 'tx_incid']]
data_covid_def

       dep       date    month   tx_incid
137     01 2020-08-02  2020-08  10.807437
138     01 2020-08-03  2020-08  10.198568
139     01 2020-08-04  2020-08  10.807437
140     01 2020-08-05  2020-08  11.264090
141     01 2020-08-06  2020-08  10.959655
...    ...        ...      ...        ...
39183  976 2021-04-05  2021-04  51.168100
39184  976 2021-04-06  2021-04  53.315013
39185  976 2021-04-07  2021-04        NaN
39186  976 2021-04-08  2021-04        NaN
39187  976 2021-04-09  2021-04        NaN

[25351 rows x 4 columns]

In [14]:
final_data_covid_df = data_covid_def[data_covid_def.date.dt.day == 15]
final_data_covid_df

       dep       date    month    tx_incid
150     01 2020-08-15  2020-08   13.851786
181     01 2020-09-15  2020-09   89.808282
211     01 2020-10-15  2020-10  333.203949
242     01 2020-11-15  2020-11  442.039409
272     01 2020-12-15  2020-12  161.350473
...    ...        ...      ...         ...
39042  976 2020-11-15  2020-11   77.288878
39072  976 2020-12-15  2020-12   49.736824
39103  976 2021-01-15  2021-01  176.046889
39134  976 2021-02-15  2021-02  913.869418
39162  976 2021-03-15  2021-03  190.001825

[808 rows x 4 columns]

Exportation des 2 fichiers en .csv pour enregistrement dans une base de données SQL

In [15]:
#Export 1ère source de données :

filtered_jobs_df.to_csv('Data/offres-alternance.csv')

#Export 2ème source de données :

final_data_covid_df.to_csv('Data/covid-incidence-dep.csv')